/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        white: "var(--color-white)",
        black: "var(--color-black)",
        gray: {
          50: "var(--color-gray-50)",
          100: "var(--color-gray-100)",
          200: "var(--color-gray-200)",
          300: "var(--color-gray-300)",
          400: "var(--color-gray-400)",
          500: "var(--color-gray-500)",
          600: "var(--color-gray-600)",
          700: "var(--color-gray-700)",
          800: "var(--color-gray-800)",
          900: "var(--color-gray-900)",
        },
        red: {
          50: "var(--color-error-50)",
          100: "var(--color-error-100)",
          200: "var(--color-error-200)",
          300: "var(--color-error-300)",
          400: "var(--color-error-400)",
          500: "var(--color-error-500)",
          600: "var(--color-error-600)",
          700: "var(--color-error-700)",
          800: "var(--color-error-800)",
        },
        yellow: {
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          400: "var(--color-warning-400)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
        },
        blue: {
          50: "var(--color-info-50)",
          400: "var(--color-info-400)",
          500: "var(--color-info-500)",
          600: "var(--color-info-600)",
          700: "var(--color-info-700)",
        },
        purple: {
          50: "var(--color-ai-50)",
          100: "var(--color-ai-100)",
          200: "var(--color-ai-200)",
          300: "var(--color-ai-300)",
          500: "var(--color-ai-500)",
          600: "var(--color-ai-600)",
          700: "var(--color-ai-700)",
          800: "var(--color-ai-800)",
        },
        teal: {
          50: "var(--color-teal-50)",
          100: "var(--color-teal-100)",
          300: "var(--color-teal-300)",
          400: "var(--color-teal-400)",
          600: "var(--color-teal-600)",
          800: "var(--color-teal-800)",
        },
        green: {
          50: "var(--color-green-50)",
          600: "var(--color-green-600)",
        },
        orange: {
          50: "var(--color-orange-50)",
          600: "var(--color-orange-600)",
        },
        primary: {
          DEFAULT: "var(--color-primary)",
          light: "var(--color-primary-light)",
          dark: "var(--color-primary-dark)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary)",
          light: "var(--color-secondary-light)",
          dark: "var(--color-secondary-dark)",
        },
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        accent: {
          50: "var(--color-accent-50)",
          100: "var(--color-accent-100)",
          200: "var(--color-accent-200)",
          400: "var(--color-accent-400)",
          500: "var(--color-accent-500)",
          DEFAULT: "var(--color-accent)",
          700: "var(--color-accent-700)",
          800: "var(--color-accent-800)",
          dark: "var(--color-accent-dark)",
        },
        blog: {
          accent: "var(--color-blog-accent)",
          "accent-dark": "var(--color-blog-accent-dark)",
        },
        text: {
          main: "var(--color-text-main)",
          heading: "var(--color-text-heading)",
          body: "var(--color-text-body)",
          secondary: "var(--color-text-secondary)",
          muted: "var(--color-text-muted)",
          placeholder: "var(--color-text-placeholder)",
          light: "var(--color-text-light)",
          lighter: "var(--color-text-lighter)",
          onPrimary: "var(--color-text-on-primary)",
          onLight: "var(--color-text-on-light)",
          link: "var(--color-text-link)",
          "link-hover": "var(--color-text-link-hover)",
          success: "var(--color-text-success)",
          error: "var(--color-text-error)",
          warning: "var(--color-text-warning)",
        },
      },
    },
  },
  plugins: [],
};
